name: Commit Stage CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build, test, quality gates
      - name: Build, test, quality gates
        run: mvn -B verify
        working-directory: contionus_integration

      # 4. Generate SBOM
      - name: Generate SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
        working-directory: contionus_integration

      # 5. Upload artifact (JAR)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: contionus_integration/target/*.jar

      # 6. Upload coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: contionus_integration/target/site/jacoco/index.html

      # 7. Docker build (lowercase repo name!)
      - name: Build Docker image
        run: docker build -t ghcr.io/natasjavitoft/continuous_integration_app:latest .

      # 8. Docker push (only on main)
      - name: Login to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/natasjavitoft/continuous_integration_app:latest
