name: Commit Stage CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build, test, and quality gates
      - name: Build, test, quality gates
        run: mvn -B verify

      # 4. Generate SBOM
      - name: Generate SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

      # 5. Upload artifact (JAR)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
